INSERT INTO websites (
  id, url, domain, ssl_certificate, display_name, tld, description,
  type, is_not_trusted, is_official, steam_login_present, verified,
  risk_score, risk_level, status, notes
) VALUES
(
  '292bfda9-757b-4f77-b623-3e0046fdc5f1',
  'https://steampowered.com',
  'steampowered.com',
  true,
  'Steam Store',
  'com',
  'Official Steam store website',
  'website',
  false,
  true,
  true,
  true,
  0,
  'none',
  'active',
  'Seeded official Steam store.'
),
(
  'a68d117c-ffc6-4b62-8dfc-ffdc54cf5403',
  'https://steamcommunity.com',
  'steamcommunity.com',
  true,
  'Steam Community',
  'com',
  'Official Steam community site',
  'website',
  false,
  true,
  true,
  true,
  0,
  'none',
  'active',
  'Seeded official Steam community.'
),
(
  '04ffc064-3938-4420-83e2-cbc61976268a',
  'https://steamdb.info',
  'steamdb.info',
  false,
  'Steam DB',
  'info',
  'Steam DB website',
  'website',
  false,
  false,
  true,
  true,
  0,
  'low',
  'active',
  ''
),
(
  '166ff50d-14f3-4b62-8af1-859a5157d986',
  'https://www.steamdeck.com',
  'steamdeck.com',
  false,
  'Steam Deck website',
  'com',
  'Steam Deck website',
  'website',
  false,
  true,
  true,
  true,
  0,
  'low',
  'active',
  ''
)
ON CONFLICT (domain) DO NOTHING;